services:
  app:
    image: auto-tests-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - db:/app/db
      - logs:/mnt/logs
      - uploads:/app/uploads
    environment:
      DB_PATH: /app/db/dbProd.sqlite
      UPLOADS_PATH: /app/uploads/
    restart: unless-stopped

volumes:
  db:   # For saving the db file dbProd.sqlite
  logs: # For saving log files in /mnt/logs
  uploads: # For uploads resources
